---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
      - name: "app"
        image: "{{ .Values.app.imageName }}"
        imagePullPolicy: Always
        command:
          - "./jokes"
          - "app:serve"
        #resources:
        #  limits:
        #    memory: "1024Mi"
        #    cpu: "2000m"
        #  requests:
        #    memory: "1024Mi"
        #    cpu: "2000m"
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
        envFrom:
          - configMapRef:
              name: "{{ .Chart.Name }}"
