#!/usr/bin/env bash

# Base
if ! source "${BASH_SOURCE%/*}/../../base"; then
  exit 1
fi

token=${USER_TOKEN:-$("${BASH_SOURCE%/*}"/../../auth/login | jq -r '.token')}

joke_id=${1:-$("${BASH_SOURCE%/*}"/../list | jq -r '.[0].id')}
from=${2:-"$RANDOM"}
to=${3:-"$RANDOM"}

# Отправляем POST-запрос для добавления аннотаций
res=$(curl -s -X POST "$api_url/$joke_url/$joke_id/$joke_annotation_url" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d '{
  "text": "test",
  "from": '"$from"',
  "to": '"$to"'
  }'
)

# Проверяем, успешно ли получение
if echo "$res" | jq -re '.error' 1>/dev/null 2>&1; then
    echo "$res" | jq 1>&2
    exit 1
fi

# Результат
echo "$res" | jq
