#!/usr/bin/env bash

# Base
if ! source "${BASH_SOURCE%/*}/../base"; then
  exit 1
fi

token=${USER_TOKEN:-$("${BASH_SOURCE%/*}"/../auth/login | jq -r '.token')}

# Отправляем POST-запрос для добавления анекдота
res=$(curl -s -X POST "$api_url/$joke_url" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d '{
  "text": "test"
  }'
)

# Проверяем, успешно ли добавление
if echo "$res" | jq -re '.error' 1>/dev/null 2>&1; then
    echo "$res" | jq 1>&2
    exit 1
fi

# Результат
echo "$res" | jq
