#!/usr/bin/env bash

api_url=${API_URL:-"http://localhost:8080/api/v1"}
health_url=${HEALTH_URL:-"readiness"}

export register_url="auth/register"
export login_url="auth/login"
export user_url="user"
export joke_url="joke"
export joke_rating_url="rating"

# Проверка доступности сервера
if ! curl "$api_url/$health_url" 1>/dev/null 2>&1; then
  echo "Server not available" 1>&2
  exit 1;
fi

# Генерация данных пользователя
export user_password=${USER_PASSWORD:-"password${RANDOM}"}
export user_username=${USER_USERNAME:-"user${RANDOM}@example.com"}
